version: '3.1'
services:
  app:
    build: .
    command: make start-dev
    restart: always
    environment:
      MYSQL_CONNECTION: root:password@tcp(db:3306)/events
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - ./:/app/

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: events
